services:
  - type: web
    name: minio
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
        sync: false
      - key: MINIO_ROOT_PASSWORD
        value: R1ghtmywrong@
        sync: false
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 10
    ports:
      - port: 9000
        name: http
      - port: 9001
        name: http
    healthCheckPath: /minio/health/live
    httpPort: 9000 